const CONTACT = {
  phone: '+52 (81) 3267-7226', phoneHref: 'tel:+528132677226', email: 'conecta@orangebee.mx', emailHref: 'mailto:conecta@orangebee.mx',
  whatsappHref: 'https://wa.me/528132677226', address: 'Av. Manuel Gómez Morín 350 PB, Valle Campestre. C.P. 66265, San Pedro Garza García, Nuevo León',
  hours: 'Lunes a Viernes: 9:00 - 18:00', social: { linkedin: 'https://www.linkedin.com/company/108113067', facebook: 'https://www.facebook.com/share/1C9zKLAWFf/?mibextid=wwXIfr' }
};
const SERVICES = [
  { id:'comercial', icon:'building-2', title:'Cobranza Comercial', descriptionShort:'Recuperación de cartera para empresas comerciales e industriales con enfoque en preservar relaciones.', description:'Recuperación especializada de cartera para el sector comercial e industrial, con estrategias diseñadas para preservar las relaciones comerciales.', featuresPreview:['Gestión preventiva','Cobranza extrajudicial','Negociación de pagos'], features:['Gestión preventiva y recordatorios','Cobranza extrajudicial amistosa','Negociación de convenios de pago','Visitas domiciliarias','Seguimiento personalizado','Reportes de gestión detallados'], stat:{value:'80%',label:'Tasa de recuperación'} },
  { id:'financiera', icon:'landmark', title:'Cobranza Financiera', descriptionShort:'Especialistas en recuperación para bancos, financieras y fintechs con altos estándares.', description:'Especialistas en recuperación de créditos para bancos, financieras y fintechs con estricto apego a la normatividad CONDUSEF.', featuresPreview:['Créditos personales','Tarjetas de crédito','Préstamos digitales'], features:['Créditos personales y nómina','Tarjetas de crédito','Préstamos digitales','Créditos automotrices','Líneas de crédito empresarial','Reestructuración de deudas'], stat:{value:'+$100M',label:'Recuperados'} },
  { id:'judicial', icon:'scale', title:'Cobranza Judicial', descriptionShort:'Representación legal para la recuperación de adeudos a través de procesos judiciales.', description:'Representación legal integral para la recuperación de adeudos mediante procedimientos judiciales y ejecución de garantías.', featuresPreview:['Demandas mercantiles','Embargos','Ejecución de garantías'], features:['Demandas mercantiles','Juicios ejecutivos','Embargo de bienes','Ejecución de garantías','Recuperación de activos','Procedimientos concursales'], stat:{value:'95%',label:'Casos resueltos'} },
  { id:'consultoria', icon:'file-text', title:'Consultoría', descriptionShort:'Asesoría integral para optimizar políticas de crédito y procesos de cobranza internos.', description:'Asesoría estratégica para optimizar políticas de crédito y procesos de cobranza internos de tu empresa.', featuresPreview:['Diagnóstico de cartera','Capacitación','Mejora de procesos'], features:['Diagnóstico de cartera','Diseño de políticas de crédito','Capacitación de equipos','Optimización de procesos','Implementación de sistemas','Mejores prácticas del sector'], stat:{value:'+100',label:'Empresas asesoradas'} }
];
const images={comercial:'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1400&q=80',financiera:'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=1400&q=80',judicial:'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=1400&q=80',consultoria:'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1400&q=80'};

const app=document.querySelector('#app');
const routes={'/':'home','/servicios':'services','/nosotros':'about','/contacto':'contact'};

const navLinks=[['Inicio','/'],['Servicios','/servicios'],['Nosotros','/nosotros'],['Contacto','/contacto']];

function layout(content){return `<header id='site-header' class='fixed top-0 left-0 right-0 z-50 transition-all duration-300 bg-transparent py-5'><div class='max-w-7xl mx-auto px-6'><div class='flex items-center justify-between'><a data-link href='/' class='flex items-center gap-2'><img src='/logo-abeja.webp' class='w-10 h-10' alt='OrangeBee logo'/><span class='font-bold text-xl text-white'><span class='text-orange-500'>Orange</span>Bee</span></a><nav class='hidden md:flex items-center gap-8'>${navLinks.map(([n,p])=>`<a data-link href='${p}' class='font-medium transition-colors ${location.pathname===p?'text-orange-500':'text-white/80 hover:text-orange-400'}'>${n}</a>`).join('')}</nav><button id='menu-btn' class='md:hidden p-2 rounded-lg text-white'><i data-lucide='menu'></i></button></div></div><div id='mobile-menu' class='md:hidden hidden bg-black/95 border-t border-white/10'><nav class='max-w-7xl mx-auto px-6 py-6 space-y-4'>${navLinks.map(([n,p])=>`<a data-link href='${p}' class='block py-2 font-medium text-white/70 hover:text-orange-500'>${n}</a>`).join('')}</nav></div></header><main id='main-content' class='flex-1'>${content}</main>${footer()}<a href='${CONTACT.whatsappHref}' target='_blank' class='fixed bottom-6 right-6 z-40 flex items-center justify-center w-14 h-14 rounded-full bg-[#25D366] text-white shadow-lg'><i data-lucide='message-circle'></i></a>`}

function footer(){return `<footer class='bg-[#080808] text-white border-t border-white/10'><div class='max-w-7xl mx-auto px-6 py-16'><div class='grid md:grid-cols-2 lg:grid-cols-4 gap-12'><div><a data-link href='/' class='flex items-center gap-2 mb-6'><img src='/logo-abeja.webp' class='w-10 h-10'><span class='font-bold text-xl'><span class='text-orange-500'>Orange</span>Bee</span></a><p class='text-neutral-300/90 text-sm leading-relaxed mb-6'>Despacho de cobranza profesional especializado en empresas, financieras y fintechs. Recuperación efectiva con ética y transparencia.</p></div><div><h4 class='font-semibold text-lg mb-6'>Enlaces</h4><ul class='space-y-3'>${navLinks.map(([n,p])=>`<li><a data-link href='${p}' class='text-neutral-300 hover:text-orange-400 text-sm'>${n}</a></li>`).join('')}</ul></div><div><h4 class='font-semibold text-lg mb-6'>Servicios</h4><ul class='space-y-3'>${SERVICES.map(s=>`<li><a data-link href='/servicios' class='text-neutral-300 hover:text-orange-400 text-sm'>${s.title}</a></li>`).join('')}</ul></div><div><h4 class='font-semibold text-lg mb-6'>Contacto</h4><ul class='space-y-3 text-neutral-400 text-sm'><li>${CONTACT.address}</li><li>${CONTACT.phone}</li><li>${CONTACT.email}</li><li>${CONTACT.hours}</li></ul></div></div></div></footer>`}

function home(){return `<section class='relative min-h-screen md:min-h-[90vh] flex items-center overflow-hidden'><div class='absolute inset-0 ob-dark-hero'><picture><source media='(min-width: 768px)' srcset='/hero-desktop.webp'><img src='/hero-mobile.webp' class='absolute inset-0 w-full h-full object-cover opacity-25'></picture></div><div class='relative z-10 max-w-7xl mx-auto px-6 py-20 w-full'><h1 class='text-4xl md:text-6xl font-bold text-white'>Recuperamos tu <span class='block text-orange-500'>cartera vencida</span></h1><p class='text-lg text-neutral-300 my-8 max-w-xl'>Soluciones profesionales de cobranza para empresas, financieras y fintechs.</p><div class='flex gap-4 flex-wrap'><a data-link href='/contacto' class='bg-orange-500 text-white px-8 py-4 rounded-xl font-semibold'>Solicitar Consulta</a><a data-link href='/servicios' class='bg-white text-neutral-900 px-8 py-4 rounded-xl font-semibold'>Conocer Servicios</a></div></div></section><section class='py-24 ob-section-soft'><div class='max-w-7xl mx-auto px-6'><h2 class='text-3xl md:text-4xl font-bold text-neutral-950 mt-3 mb-8 text-center'>Soluciones Integrales de Cobranza</h2><div class='grid md:grid-cols-2 lg:grid-cols-4 gap-6'>${SERVICES.map(s=>`<div class='bg-white rounded-2xl p-6 border border-neutral-200'><img src='${images[s.id]}' class='w-full h-40 object-cover rounded-xl mb-4'><h3 class='text-xl font-bold text-neutral-900 mb-2'>${s.title}</h3><p class='text-neutral-600 text-sm mb-4'>${s.descriptionShort}</p></div>`).join('')}</div></div></section>`}

function services(){return `<section class='ob-dark-hero pt-32 pb-24 text-center'><h1 class='text-4xl md:text-5xl font-bold text-white'>Soluciones Integrales de Cobranza</h1></section><section class='py-24 ob-section-soft'><div class='max-w-7xl mx-auto px-6 space-y-20'>${SERVICES.map((s,i)=>`<div class='grid lg:grid-cols-2 gap-16 items-center'><div class='${i%2?'lg:order-2':''}'><h2 class='text-3xl font-bold text-neutral-900 mb-4'>${s.title}</h2><p class='text-neutral-600 text-lg mb-6'>${s.description}</p><ul class='grid sm:grid-cols-2 gap-3'>${s.features.map(f=>`<li class='text-neutral-600'>• ${f}</li>`).join('')}</ul></div><div><img src='${images[s.id]}' class='rounded-3xl'></div></div>`).join('')}</div></section>`}
function about(){return `<section class='ob-dark-hero pt-32 pb-24 text-center'><h1 class='text-4xl md:text-5xl font-bold text-white'>Conoce a OrangeBee</h1></section><section class='py-24 ob-section-soft'><div class='max-w-4xl mx-auto px-6 text-neutral-700 space-y-6'><p>OrangeBee surge de la necesidad de transformar la industria de cobranza en México.</p><p>Atendemos empresas, financieras y fintechs que buscan un socio estratégico para la recuperación de su cartera vencida.</p></div></section>`}
function contact(){return `<section class='ob-dark-hero pt-32 pb-24 text-center'><h1 class='text-4xl md:text-5xl font-bold text-white'>Hablemos de tu Cartera</h1></section><section class='py-24 ob-section-soft'><div class='max-w-3xl mx-auto px-6'><form id='contact-form' class='bg-white rounded-3xl p-8 border border-neutral-200 space-y-6'><input required name='name' placeholder='Nombre completo' class='w-full rounded-xl border border-neutral-300 p-3'><input required type='email' name='email' placeholder='Correo electrónico' class='w-full rounded-xl border border-neutral-300 p-3'><textarea required name='message' rows='5' placeholder='Cuéntanos sobre tu cartera...' class='w-full rounded-xl border border-neutral-300 p-3'></textarea><button class='w-full bg-orange-500 text-white py-4 rounded-xl font-semibold'>Enviar Mensaje</button></form></div></section>`}

function render(){
  const path=location.pathname.replace('/OB-React','')||'/';
  const page=routes[path];
  const content = page==='home'?home():page==='services'?services():page==='about'?about():page==='contact'?contact():`<div class='min-h-screen flex items-center justify-center ob-section-soft'><div class='text-center'><h1 class='text-7xl text-neutral-400'>404</h1><p class='text-neutral-700'>Página no encontrada</p><a data-link href='/' class='inline-block mt-4 bg-orange-500 text-white px-6 py-3 rounded-xl'>Volver al inicio</a></div></div>`;
  app.innerHTML=layout(content);
  bind();
  lucide.createIcons();
  window.scrollTo({top:0});
  document.title = page ? `OrangeBee | ${page==='home'?'Cobranza Inteligente y Recuperación de Cartera':page[0].toUpperCase()+page.slice(1)}` : 'Página no encontrada | OrangeBee';
}

function bind(){
  document.querySelectorAll('[data-link]').forEach(a=>a.addEventListener('click',e=>{if(a.target==='_blank')return; e.preventDefault(); history.pushState({},'',a.getAttribute('href')); render();}));
  const btn=document.querySelector('#menu-btn'); const menu=document.querySelector('#mobile-menu'); if(btn) btn.addEventListener('click',()=>menu.classList.toggle('hidden'));
  window.addEventListener('scroll',()=>{const h=document.querySelector('#site-header'); if(!h) return; if(scrollY>20){h.classList.add('bg-black/75','backdrop-blur-xl','border-b','border-orange-500/20','py-3'); h.classList.remove('py-5');} else {h.classList.remove('bg-black/75','backdrop-blur-xl','border-b','border-orange-500/20','py-3'); h.classList.add('py-5');}}, {passive:true});
  const form=document.querySelector('#contact-form');
  if(form) form.addEventListener('submit',(e)=>{e.preventDefault(); const fd=new FormData(form); const subject=`Nuevo contacto desde OrangeBee - ${fd.get('name')||'Sin nombre'}`; const body=`Mensaje:\n${fd.get('message')}`; location.href=`mailto:conecta@orangebee.com.mx?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;});
}

window.addEventListener('popstate', render);
render();
setTimeout(()=>document.querySelector('#app-loader')?.classList.add('fade-out'),250);
setTimeout(()=>document.querySelector('#app-loader')?.remove(),500);
